version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/iic2173-proyecto-semestral-grupo-16v2/backend
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 600
      runas: ec2-user
  BeforeInstall:
    - location: cleanupScript.sh
  AfterInstall:
    - location: install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 600
      runas: ec2-user