version: '3'
services:
  web:
    build: .
    command: bash -c "bundle exec rake db:migrate && bundle exec rails s -p 80 -b '0.0.0.0'"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    env_file:
      .env.prod

